type = "directrequest"
schemaVersion = 1
name = "Meta Data Processor - Beta"
contractAddress = ""
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="bridge" name="upload-meta-data" requestData="{\\"data\\":{\\"weaponClass\\": $(decode_cbor.weaponClass),\\"weaponRarity\\": $(decode_cbor.weaponRarity), \\"weaponModifier\\": $(decode_cbor.weaponModifier),\\"dob\\": $(decode_cbor.dob)}, \\"id\\": $(jobSpec.externalJobID)}"]
    parse        [type="jsonparse" path="url" data="$(fetch)"]
    
    encode_data  [type="ethabiencode" abi="(bytes32 requestId, bytes value)" data="{\\"requestId\\": $(decode_log.requestId), \\"value\\": $(parse)}"]

    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="0x5A689Fa6e2Afe2765158F6Ee234f083969022b20" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> encode_data -> encode_tx -> submit_tx
"""
externalJobID = "132b0125-be0f-4435-8e0b-384f5af81020"


